### ISSUE TITLE
Big todo list

### ISSUE THREAD

**Issue by Candoran2** [Candoran2/new-pyffi#1]
### General codegen
 - [x] Move most of the \_\_str\_\_ functionality of the classes to class methods that can be called to prevent infinite recursion.

### File reading
- [x] Adjust header code to update the basics _right_ after reading the endianness, instead of first reading the entire header (because some basics already show up in the header).
- [x] Add ExportString source code to simply return a string.
- [x] Make function to gather Refs/Pointers and update the attributes to point towards the niobjects.
- [x] Add footer reading exception for NeoSteam.
- [x] Fix NiDataStream usage and access reading.
- [x] Change StringPalette to return a list of strings.

### File writing
- [x] Make nif file writing possible.
   - [x] Make function to gather and sort all NiObjects from one or multiple root blocks.
   - [x] Make header/footer writing function.
- [x] Fix NiDataStream usage and access writing.

### Spells and utils
- [ ] Update the spells and utils to use the new library and methods of accessing objects.

### Interface of created objects
- [x] Port code of vector/matrix classes to the new format.
- [ ] Make NiObject.tree more efficient for unique=True - probably not necessary, it's not used often and tree is fast enough.
- [x] Make get_links, gets_refs and get_strings more efficient through class variables.
- [ ] Port code of other objects
   - [x] Crude port of code
   - [x] Update on the following blocks/structs to use havok scale instead of hardcoded 7:
          - bhkPackedNiTriStripsShape
          - BhkLimitedHingeConstraintCInfo (previously LimitedHingeDescriptor)
          - BhkRagdollConstraintCInfo (previously RagdollDescriptor)
   - [ ] Unify bhkHingeConstraintCInfo and bhkLimitedHingeConstraintCInfo to make limited inherit from normal hinge?
   - [ ] Update tangent space generation code.
- [x] NifFile object creation from version, user version and bs version.
- [x] Update bhkPackedNiTriStripsShape not to use update_size().
- [ ] Refactor NiPixelFormat save_as_dds to reuse shared (e.g, setting of caps etc).

### Optimization
- [ ] Create numpy array reading and writing functions for simple structs like Vectors, Colors etc.
- [ ] Numpy array reading and writing functions for bitfields and enums whose storage have array reading/writing functions?
- [ ] Created ragged array functions for basics with numpy equivalents.

### Long term (potentially breaking changes)
- [ ] Update vector and matrix classes to use numpy under the hood for increased compatibility with other libraries and standard convention (specifically conventions about matrix/elementwise multiplication, see also numpy.dot and https://peps.python.org/pep-0465/).
- [ ] The String and FilePath classes seem to be identical. Is there any difference between them other than the places where they are used?
- [ ] Change `BSTriShape\Skin` to `BSTriShape\Skin Instance` to agree with the NiGeometry class? Or maybe even have BSTriShape inherit from NiGeometry directly?
